_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.20
            "5": 0.19.5
            "8":
                - 5
            "12": 0.19.5
            "13": darwin-x86_64
epochs:
    value: 100000
learning_rate:
    value: 0.001
